---

- name: checking variables at task level
  hosts: localhost
  become: yes
  tasks:
  - name: task1, defining variables 
    vars:
      town: "Ongole"
      dist: "prakasham"
    ansible.builtin.debug:
      #msg: "hello {{town}}" 
  - name: task2, defining variables 
    vars:
      town: "kandukur"
      dist: "telangana"
    ansible.builtin.debug:
      