---

- name: nginx installation and running
  hosts: web #deleting nginx from web host
  become: yes
  tasks:
  - name: remove nginx
    ansible.builtin.package:
      name: nginx
      state: absent
