---

- name: checking vars through prompts
  hosts: localhost
  become: yes
  vars_prompt:
  - name: US
    prompt: please enter
    private: false # everyone sees what we enter
  - name: UP
    prompt: passwd
    private: true # to enter passwd in secret
  tasks:
  - name: check prompts
    ansible.builtin.debug:
      msg: "enter passwd {{US}}, enter passwd {{UP}}"