---

- name: checking variables at task level
  hosts: localhost
  become: yes
  tasks:
  - name: task1, defining variables 
    vars:
      town: "Ongole"
      dist: "prakasham"
    ansible.builtin.debug:
      msg: "hello {{town}}" # if u dont call variables they will return hello world!

  - name: task2, defining variables 
    vars:
      town: "kandukur"
      dist: "telangana"
    ansible.builtin.debug:
    # here ansible defaulty prints hello world  