---

- name: checking variables using files
  hosts: localhost
  vars_files: # this is important, specifiy the file name of variables here for ansible to refer and do task.
  - 06varfile.yaml
  become: yes
  tasks:
  - name: task1
    ansible.builtin.debug:
      msg: "established {{estd}}"
      