---

- name: checking loops
  hosts: web
  become: yes
  tasks:
  - name: task1, creating loops
    ansible.builtin.debug:        # in ansible variables are called using {{<variable-name>}}
      name: "{{item}}"   # item is the default keyword of ansible to execute a loop
    loop:                        # specifying loops
    - {name: 'git',state: 'present'}
    - {name: 'jq',state: 'absent'}