- name: installing sql
  hosts: sql
  become: yes
  tasks:
  - name: disabling and enabling sql version
    ansible.builtin.command: dnf module disable mysql:18 -y

  - name: setup our own sql repo 
    ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

  - name: downloading mysql 
    ansible.builtin.dnf:
      name: mysql-community-server -y
      state: present 

  - name: enable and start mysql service
    ansible.builtin.service:
      name: mysqld    
      enabled: yes
      state: restarted

  - name: set root passwd 
    ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1    