- name: installing rabbitmq
  hosts: rabbitmq
  become: yes
  tasks:
  - name: configure erlang repo
    ansible.builtin.shell: https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

  - name: configure rabbitmq repo
    ansible.builtin.shell: https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

  - name: install rabbitMQ 
    ansible.builtin.dnf:
      name: rabbitmq-server
      state: present

  - name: enable and start rabbitMQ 
    ansible.builtin.service: 
      name: rabbitmq-server
      enabled: yes
      state: restarted

  - name: create rabbitmq user
    ansible.builtin.command: rabbitmqctl add_user roboshop roboshop123

  - name: setting permissions for user
    ansible.builtin.command: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"              